//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collections_detail
    {
        public int collection_id { get; set; }
        public string member_id { get; set; }
        public string tourism_id { get; set; }
        public bool privacy { get; set; }
        public int collection_type_id { get; set; }
    
        public virtual collection_type collection_type { get; set; }
        public virtual member member { get; set; }
    }
}
