//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_profile
    {
        public string member_id { get; set; }
        public string member_name { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string nickname { get; set; }
        public System.DateTime create_time { get; set; }
        public string nation { get; set; }
        public string city { get; set; }
        public string address_detail { get; set; }
        public string email { get; set; }
        public Nullable<bool> emailConfirmed { get; set; }
        public string phone { get; set; }
        public string profile_photo { get; set; }
        public string website_link { get; set; }
        public string brief_intro { get; set; }
        public string cover_photo { get; set; }
        public Nullable<int> member_score { get; set; }
    
        public virtual member member { get; set; }
    }
}
