//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public message()
        {
            this.message_emoji_details = new HashSet<message_emoji_details>();
        }
    
        public long msg_id { get; set; }
        public System.DateTime msg_time { get; set; }
        public string msg_content { get; set; }
        public long comment_id { get; set; }
        public string member_id { get; set; }
        public Nullable<bool> msg_status { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual member member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<message_emoji_details> message_emoji_details { get; set; }
    }
}
